keys: 
  - &xanderio age1ftsxs8qj86g6v28f69qalwg2a85rd0vxh8zm304k3p4uv63x5yesd44w56
  - &valen age1su39hcctpl3fkya306zfw28h8dg869mtud07us7ynwz5xcylecrqu46cjv
  - &vetinari age1w5u4meu5hnuwsylwnfut7le2pm5n37h8wk9mny9jw242jc9nhynq2lt7fx
  - &carrot age1vnu25nrzx8535t2x9exp8uger5x25tj4ak309rdjfw6mhetqeekqu6c0cc
  - &drumknott age1hp7yy04hmhepxteukn083lrfr23aep220gqqpwq2j3q86janf5wqrls6ss

creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - age:
        - *xanderio
        - *valen
        - *vetinari
        - *carrot
        - *drumknott

  # hosts
  - path_regex: secrets/hosts/valen.yaml
    key_groups:
      - age:
        - *xanderio
        - *valen
  - path_regex: secrets/hosts/vetinari.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari
  - path_regex: secrets/hosts/carrot.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  # services
  - path_regex: secrets/services/synapse.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/mas-synapse.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/authentik.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/miniflux.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/ddclient.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari

  - path_regex: secrets/services/grafana.yaml
    key_groups:
      - age:
        - *xanderio
        - *valen

  - path_regex: secrets/services/paperless.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari

  - path_regex: secrets/services/outline.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/stalwart.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/grist.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/mealie.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  - path_regex: secrets/services/garage.yaml
    key_groups:
      - age:
        - *xanderio
        - *drumknott

  - path_regex: secrets/services/immich.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari

  - path_regex: secrets/services/docs.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot
