keys: 
  - &xanderio age1ftsxs8qj86g6v28f69qalwg2a85rd0vxh8zm304k3p4uv63x5yesd44w56
  - &delenn age1hzrrta33n0rpatlu72sjdvv7r7nkaf0rjhhszue0ltr9l7c8zyuqzefgqx
  - &valen age1su39hcctpl3fkya306zfw28h8dg869mtud07us7ynwz5xcylecrqu46cjv
  - &vetinari age1w5u4meu5hnuwsylwnfut7le2pm5n37h8wk9mny9jw242jc9nhynq2lt7fx
  - &gregtech age1jnswz6rvnya72fhcq48thvgdgyzztw5yf87ku7gffvjgcrl5yews0y5qfp
  - &carrot age1vnu25nrzx8535t2x9exp8uger5x25tj4ak309rdjfw6mhetqeekqu6c0cc

creation_rules:
  - path_regex: secrets/all/[^/]+\.yaml$
    key_groups:
      - age:
        - *xanderio
        - *delenn
        - *valen
        - *vetinari
        - *gregtech
        - *carrot

  # hosts
  - path_regex: secrets/hosts/delenn.yaml
    key_groups:
      - age:
        - *xanderio
        - *delenn
  - path_regex: secrets/hosts/valen.yaml
    key_groups:
      - age:
        - *xanderio
        - *valen
  - path_regex: secrets/hosts/vetinari.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari
  - path_regex: secrets/hosts/carrot.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot

  # services
  - path_regex: secrets/services/synapse.yaml
    key_groups:
      - age:
        - *xanderio
        - *delenn
        - *carrot

  - path_regex: secrets/services/authentik.yaml
    key_groups:
      - age:
        - *xanderio
        - *delenn
        - *carrot

  - path_regex: secrets/services/miniflux.yaml
    key_groups:
      - age:
        - *xanderio
        - *delenn
        - *carrot

  - path_regex: secrets/services/ddclient.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari

  - path_regex: secrets/services/grafana.yaml
    key_groups:
      - age:
        - *xanderio
        - *valen

  - path_regex: secrets/services/paperless.yaml
    key_groups:
      - age:
        - *xanderio
        - *vetinari

  - path_regex: secrets/services/outline.yaml
    key_groups:
      - age:
        - *xanderio
        - *carrot
