# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c7ed6a10-9d98-424b-80c6-c8c6fcdf8387";
    fsType = "ext4";
  };

  fileSystems."/mnt/nextcloud" = {
    device = "/dev/disk/by-uuid/23d2c8f1-662a-468e-b884-5230c9ebce6f";
    fsType = "ext4";
  };

  fileSystems."/mnt/paperless" = {
    device = "/dev/disk/by-uuid/f840e9a5-e709-46be-9dec-338e1ceebf5a";
    fsType = "ext4";
  };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
