name: Update Treesitter grammars

on:
  schedule:
    # every day at 8am UTC
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  updates:
    name: "Update Treesitter grammars"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{secrets.PAT}}"
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "treesitter grammars: update"
        run: |
          git config user.name 'github-actions'
          git config user.email 'action@github.com'
          cd pkgs/nvim-ts-grammars
          ./updater.py
          git add .
          if ! git diff --cached --quiet; then
            git commit -m 'pkgs/nvim-ts-grammars: update'
            git push
          fi
